### ISSUE TITLE
Remove react-syntax-highlighter package

### ISSUE THREAD

**Issue by holgerdell** [SEAL-Self-Assessment-and-Learning/algo-learn#38]
Can the react-syntax-highlighter package already be removed? If yes, do so.
https://github.com/goethe-tcs/algo-learn/blob/d72c0554556a9fc34d262f4ee2c6698972d72b4e/front-end/src/components/Markdown.tsx#L3

**Comment by Fabianstw** [comment]
In the commit [84465ad](https://github.com/SEAL-Self-Assessment-and-Learning/algo-learn/commit/84465ade3f5d9d352cb59493abe17cba4c090987) I removed the `react-syntax-highlighter` package and changed little react to display `json` and `tex`. 

In doing so, the issue should now be resolved.
