### ISSUE TITLE
Unnecessary expressions?

### ISSUE THREAD

**Issue by holgerdell** [SEAL-Self-Assessment-and-Learning/algo-learn#39]
The linter found many expressions that have no effect:

https://github.com/SEAL-Self-Assessment-and-Learning/algo-learn/blob/ecce252c4709c10f278a411b82334e39ac50de6f/shared/src/question-generators/time/utils.ts#L383

Figure out whether they are needed and either fix them or remove them.

**Comment by Fabianstw** [comment]
Yes, I think that is because of a linter update. I fixed those in the PR37 (refactor-loops)

**Comment by Fabianstw** [comment]
PR [d17800d](https://github.com/SEAL-Self-Assessment-and-Learning/algo-learn/commit/d17800d3a787fa2ffcba0d8cf83523e872a3f164) hat das Problem behoben. Pushes auf main laufen wieder ohne Problem durch 👍
